// 零依赖 CommonJS 打包器，仅处理本项目使用的静态相对路径 require。
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const modules = new Map();
function visit(file) {
  const id = path.relative(root, file).split(path.sep).join('/');
  if (modules.has(id)) return id;
  modules.set(id, '');
  const source = fs.readFileSync(file, 'utf8').replace(/require\(['"](\.[^'"]+)['"]\)/g, (_, relative) => {
    let target = path.resolve(path.dirname(file), relative);
    if (!path.extname(target)) target += '.js';
    return `require(${JSON.stringify(visit(target))})`;
  });
  modules.set(id, source); return id;
}
const entry = visit(path.join(root, 'web/entry.js'));
const bundle = `/* Generated by npm run build. */\n(function(){\nconst modules={\n${[...modules].map(([id, code]) => `${JSON.stringify(id)}:function(require,module,exports){\n${code}\n}`).join(',\n')}\n};\nconst cache={};function require(id){if(cache[id])return cache[id].exports;const module=cache[id]={exports:{}};modules[id](require,module,module.exports);return module.exports;}require(${JSON.stringify(entry)});\n})();\n`;
fs.writeFileSync(path.join(root, 'web/bundle.js'), bundle);
console.log(`浏览器版本已生成：${modules.size} 个模块，${Buffer.byteLength(bundle)} 字节`);
